### PR TITLE
Fixing UI for degree details form - submit form button

### PR DESCRIPTION
**Pull request by jennifermtan**
FIxing issue #25

### CODE REVIEW

**Review by GoodGameRuler — COMMENTED** [review]
For some reason the font is being displayed on my screen as it does on yours. Specifically, the submit button. Could you look into that.

image

**Comment by jennifermtan** [comment]
> For some reason the font is being displayed on my screen as it does on yours. Specifically, the submit button. Could you look into that.
> 
> image

Hmm that's weird! Also for the nav bar texts. Should I make a different issue for this?

**Comment by jennifermtan** [comment]
> > For some reason the font is being displayed on my screen as it does on yours. Specifically, the submit button. Could you look into that.
> > image
> 
> Hmm that's weird! Also for the nav bar texts. Should I make a different issue for this?

**Comment by GoodGameRuler** [comment]
> > For some reason the font is being displayed on my screen as it does on yours. Specifically, the submit button. Could you look into that.
> > image
> 
> Hmm that's weird! Also for the nav bar texts. Should I make a different issue + PR for this?

Yes thank you. Please add the `os-browser specific` label. I will approve changes however, you cannot merge into main as your branch is a few commits behind main. Please merge main into branch. However, I will enable auto-merge for now.

**Review by GoodGameRuler — APPROVED** [review]

**Comment by GoodGameRuler** [comment]
Never mind @jennifermtan , there was an update branch button.

**Pull request merged**
