### PR TITLE
Finish UI for About Us page

### PR DESCRIPTION
**Pull request by jennifermtan**
Let me know if you want me to add anything to the content!

### CODE REVIEW

**Comment by GoodGameRuler** [comment]
Couple of things

- [ ] I think the GitHub icons are a bit too big but subjective.

More importantly, you've created a redundant class.

image

- [ ] Merge the classes if you intend to change all page headers to 50px, however, if you want only the about us page to have 50px, add that as another class. You can have multiple classes in the class tag className = "class1 class2".

- [ ] Lastly, there are some console errors if you could fix that that would be legendary.

**Comment by jennifermtan** [comment]
Fixed! @GoodGameRuler Please merge if you think this is good

**Comment by GoodGameRuler** [comment]
# Last Edits
With the profile pictures I changed the size from 100px to 60px. They were still too large. 

## 60px
image

## 100px
image

## Remaining Issues
_Normally I would correct this myself but then I think that makes the whole of reviews pointless_
_I'll try to catch all these issues the first time around_
- [ ] Please look at this link for up for static image placement. https://nextjs.org/docs/pages/building-your-application/optimizing/static-assets. TLDR: Images should be placed in the public dir (or possibly static dir) in the root dir.
- [ ] Remove any element css tags (a, hr, ...) and replace with class names
- [ ] Abstract common class info (.jenny, .udit, .parth, .devu,.githubSVG) into a common class like .profilePhoto or make another class and add it to the class list. 
- [ ] Rename/Restructure classes like .body
  - To Either a more accurate class name like aboutUsDescription
  - If you think that this is the font types and stuff that you want for the entire website apply it to all a, em, .. tags in reset.css

## Last things
- [ ] Was meaning to say, more of a recommendation from last time, try figuring out how to use chrome developer console (inspect element). Probably figure out why your inspect element shows up on the new page
  - Why? Because if you want to fiddle with font sizes and stuff its way easier when you have live preview.

These are mostly minor changes. The about us page looks legendary, thanks for adding Devanshi and Parth to the contributors section!

**Comment by jennifermtan** [comment]
- [ ] Instead of "Meet the Current Team", change to "Maintainers" and "Contributors"

**Comment by jennifermtan** [comment]
@GoodGameRuler Done! For the images I changed to 80px - do you think this is still too large? Feel free to change :)
Screenshot 2024-05-18 at 11 30 46 AM

**Review by GoodGameRuler — APPROVED** [review]
Looks good.

**Comment by GoodGameRuler** [comment]
I'm going to approve these changes but @jennifermtan we should figure out why the difference in font is happening.

**Pull request merged**
